---
# file: webservers.yml
- hosts: kibanaservers
  remote_user: vagrant
  become: yes
  become_user: root
  gather_facts: yes
  roles:
    - common
    - elasticsearch
    - kibana
    - logstash
    - apache-loggen
